export const GET_TEST_DATA_EPIC = 'GET_TEST_DATA_EPIC';
export const GET_TEST_DATA_SUCCESS = 'GET_TEST_DATA_SUCCESS';
export const GET_TEST_DATA_ERROR = 'GET_TEST_DATA_ERROR';
export const GET_TEST_DATA_LOADING = 'GET_TEST_DATA_LOADING';
export const GET_TEST_DATA_CANCEL = 'GET_TEST_DATA_CANCEL';
